apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: lab3
  name: host-pvc
spec:
  storageClassName: localstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi