apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: lab3
  name: host-pv
spec:
  storageClassName: localstorage
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/mysql
  capacity:
    storage: 4Gi